server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Karim-Isaias/Upgrade-Users-API
          search-paths: config-data
  application:
    name: config-service
