server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/**
          filters:
            - RemoveRequestHeader=Cookie

keycloak:
  realm: client
  auth-server-url: http://localhost:9090
  resource: client
  public-client: true
  bearer-only: true
