server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/**
          filters:
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/client/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/client/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/client/protocol/openid-connect/token
        registration:
          client:
            provider: keycloak
            client-id: client
            client-secret: hazvY1A8o0slGyjYFOdQYwEW1zG9JAm5
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/client"
