eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/users_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: secret
    username: mysqluser
   #mostar por consola los datos de los queries
  jpa:
    show-sql: true
    #autogenera las tablas
    hibernate:
      ddl-auto: update
    #dialecto de las base de datos
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: profile-service
          uri: lb://basic
          predicates:
            - Path=/profile/**