server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      

spring:
  application:
    zipkin: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:13306/users_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: secret
    username: mysqluser
   #mostar por consola los datos de los queries
  jpa:
    show-sql: true
    #autogenera las tablas
    hibernate:
      ddl-auto: update
    #dialecto de las base de datos
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
